### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by rmcgibbo** [selassid/canopener#3]
I received the following error from `pip install canopener`, on OS X 10.10, python 3.4.2

```
rmcgibbo@MacBook-Pro  ~/projects/bibtagger (3.4.2) ‹master*›
$ pip install canopener
Collecting canopener
  Downloading canopener-0.1.5.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/4q/r0z3jgtj3p51kvjgm4tcxsc40000gn/T/pip-build-kkdvye5g/canopener/setup.py", line 17, in <module>
        license=resource_string(__name__, 'LICENSE.txt'),
      File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/setuptools-12.1-py3.4.egg/pkg_resources/__init__.py", line 1141, in resource_string
      File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/setuptools-12.1-py3.4.egg/pkg_resources/__init__.py", line 1569, in get_resource_string
      File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/setuptools-12.1-py3.4.egg/pkg_resources/__init__.py", line 1649, in _get
    NotImplementedError: Can't perform this operation for loaders without 'get_data()'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/var/folders/4q/r0z3jgtj3p51kvjgm4tcxsc40000gn/T/pip-build-kkdvye5g/canopener/setup.py", line 17, in <module>

        license=resource_string(__name__, 'LICENSE.txt'),

      File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/setuptools-12.1-py3.4.egg/pkg_resources/__init__.py", line 1141, in resource_string

      File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/setuptools-12.1-py3.4.egg/pkg_resources/__init__.py", line 1569, in get_resource_string

      File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/setuptools-12.1-py3.4.egg/pkg_resources/__init__.py", line 1649, in _get

    NotImplementedError: Can't perform this operation for loaders without 'get_data()'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/4q/r0z3jgtj3p51kvjgm4tcxsc40000gn/T/pip-build-kkdvye5g/canopener
```

**Comment by davidselassie** [comment]
Ok, should have gotten this sorted out now and made the basics run on py34. Try out v0.1.6.
